### ISSUE TITLE
console.pingone.com "REDIRECT URLS" validation error "http://localhost is not a valid URL. https is required."

### ISSUE THREAD

**Issue by 1koval** [pingidentity/pingone-customers-sample-oidc#10]
[Tutorial Video](https://youtu.be/TBA5VTfnsSE) detailing the implementation of this sample referenced at [javascript/README.md](https://github.com/pingidentity/pingone-customers-sample-oidc/blob/master/javascript/README.md)).

When I try to reproduce steps (as [on video at 1:22](https://www.youtube.com/watch?v=TBA5VTfnsSE&t=82s)) I got:
"REDIRECT URLS" validation error "`http://localhost is not a valid URL. https is required.`"

It could be:
- [ ]  a bug in https://console.pingone.com/ web UI
- [ ]  or a change in PingOne security policy
- [ ]  or special console settings somewhere.

It would be nice to clarify it as it may require changes in the documentation or example code.

**Comment by jason-hatchett** [comment]
Hi koval, thanks for the heads up. I believe we had a regression in UI permissions. We have a ticket to fix this, and then it should work as described in the video. We'll update this when the issue is resolved.

**Comment by jason-hatchett** [comment]
This has now been resolved.
