### ISSUE TITLE
Doesn't work on IE/Edge (but does on Chrome)

### ISSUE THREAD

**Issue by joelrader** [pingidentity/pingone-customers-sample-oidc#7]
I've been able to successfully deploy this code to an NGINX Docker container with SSL enabled and sign-in successfully on a Chrome browser (Windows). However, I can't get it to work on either IE or Edge. Have not tried Safari.

When I click "Sign On" in the browser after first loading up the page, it simply does nothing.

**Comment by hkrop** [comment]
It works on Safari Version 12.1.1 (14607.2.6.1.1)
Will test it on IE

**Comment by hkrop** [comment]
Since the last comment was on Jul 3, 2019  - assume this issue not actual now. Please reopen it if there are still any questions
