### ISSUE TITLE
Sample code should parse out Address attribute? Just shows [Object object]

### ISSUE THREAD

**Issue by joelrader** [pingidentity/pingone-customers-sample-oidc#8]
When I sign in a user that has a value for the "Street Address" field, like "123 Main St", it doesn't show in the User or Token details. Just [Object object] is shown.

Does the address attribute come from the Street Address attribute? Looks like the JSON object needs to be converted to a string?

**Comment by hkrop** [comment]
Added a fix [in this commit](https://github.com/pingidentity/pingone-customers-sample-oidc/commit/95fcdf4388990c6f6f84634abe8495462fd35dbf)
